# Workflow for generating CHANGELOG.md, creating a GitHub release tag, and bumping the project version.
# Powered by https://github.com/googleapis/release-please and https://github.com/googleapis/release-please-action

name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # use a PAT (personal access token) so it can trigger other workflows
          token: ${{ secrets.GITHUB_TOKEN }}
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          # release-type: simple
          
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json
